name: message_slot_bubblegum
description: "Flutter widget to help you pop your messages"
version: 0.3.0
homepage: https://github.com/flarebyte/message_slot_bubblegum

environment:
  sdk: ^3.4.4
  flutter: "3.24.0"

dependencies:
  flutter:
    sdk: flutter
  grand_copperframe:
    git:
      url: https://github.com/flarebyte/grand_copperframe.git
      ref: v0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

